forwardings:
  - PromptForRegisteringCausesRegistrationRequest
      op-fc-0000
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/register-yourself
              op-s-0000
        fc-port-update:
          - /v1/register-yourself
              op-s-0000
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
        - /v1/register-yourself
            op-s-0000
      consequent-requests:
        unicast:
          - RegistryOffice://v1/register-application
              op-c-0020
  - PromptForEmbeddingCausesRequestForBequeathingData
      op-fc-0001
      Invariant Process Snippet
      management-requests:
        operation-client-update:
        fc-port-update:
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
        - /v1/embed-yourself
            op-s-0001
      consequent-requests:
        unicast:
        - OldRelease://v1/bequeath-your-data-and-die
            op-c-0000
  - ServiceRequestCausesLoggingRequest
      op-fc-0002
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/redirect-service-request-information
              op-s-0002
        fc-port-update:
          - /v1/redirect-service-request-information
              op-s-0002
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
        - /v1/register-yourself
            op-s-0000
        - /v1/embed-yourself
            op-s-0001
        - /v1/redirect-service-request-information
            op-s-0002
        - /v1/redirect-oam-request-information
            op-s-0003
        - /v1/end-subscription
            op-s-0004
        - /v1/inquire-oam-request-approvals
            op-s-0005
        - /v1/update-client
            op-s-0007
        - /v1/list-ltps-and-fcs
            op-s-0008
        - /v1/redirect-topology-change-information
            op-s-0009
        - /v1/update-operation-key
            op-s-0010
        - /v1/update-operation-client
            op-s-0011
        - /v1/bequeath-your-data-and-die
            op-s-1000
        - /v1/inform-about-application
            op-s-2001
        - /v1/inform-about-application-in-generic-representation
            op-s-2002
        - /v1/inform-about-release-history
            op-s-2003
        - /v1/inform-about-release-history-in-generic-representation
            op-s-2004
        - /v1/start-application-in-generic-representation
            op-s-3000
        ## All service requests to be complemented
      consequent-requests:
        unicast:
          - ExecutionAndTraceLog://v1/record-service-request
              op-c-0040
  - OamRequestCausesLoggingRequest
      op-fc-0003
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/redirect-oam-request-information
              op-s-0003
        fc-port-update:
          - /v1/redirect-oam-request-information
              op-s-0003
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
      consequent-requests:
        unicast:
          - OamLog://v1/record-oam-request
              op-c-0050
  - OamRequestCausesInquiryForAuthentication
      op-fc-0004
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/inquire-oam-request-approvals
              op-s-0005
        fc-port-update:
          - /v1/inquire-oam-request-approvals
              op-s-0005
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
      consequent-requests:
        unicast:
          - AdministratorAdministration://v1/approve-oam-request
              op-c-0060
  ## Forwardings for configuring INDIVIDUAL subscriptions on NewRelease

  ## Forwardings for transferring data to NewRelease

  ## Forwardings for creating INDIVIDUAL subscriptions to NewRelease

  ## Forwardings for ending INDIVIDUAL subscriptions to OldRelease

  - PromptForBequeathingDataCausesRequestForBroadcastingInfoAboutServerReplacement
      op-fc-0105
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/embed-yourself
              op-s-0001
        fc-port-update:
          - /v1/embed-yourself
              op-s-0001
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
        - /v1/bequeath-your-data-and-die
            op-s-1000
      consequent-requests:
        unicast:
          - RegistryOffice://v1/relay-server-replacement
              op-c-0021
  - PromptForBequeathingDataCausesRequestForDeregisteringOfOldRelease
      op-fc-0106
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/embed-yourself
              op-s-0001
        fc-port-update:
          - /v1/embed-yourself
              op-s-0001
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
        - /v1/bequeath-your-data-and-die
            op-s-1000
      consequent-requests:
        unicast:
          - RegistryOffice://v1/deregister-application
              op-c-0022
  - PromptingNewReleaseForUpdatingServerCausesRequestForBroadcastingInfoAboutBackwardCompatibleUpdateOfOperation
      op-fc-0107
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/embed-yourself
              op-s-0001
        fc-port-update:
          - /v1/embed-yourself
              op-s-0001
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
        - /v1/update-client
            op-s-0007
      consequent-requests:
        unicast:
          - RegistryOffice://v1/relay-operation-update
              op-c-0023
  - PromptForRedirectingTopologyInformationCausesSendingAnInitialStateToALT
      op-fc-0005
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
        - /v1/redirect-topology-change-information
            op-s-0009
      consequent-requests:
        unicast:
          - ApplicationLayerTopology://v1/update-all-ltps-and-fcs
              op-c-0070
  - ServiceRequestCausesLtpUpdateRequest
      op-fc-0006
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
        - /v1/register-yourself
            op-s-0000
        - /v1/embed-yourself
            op-s-0001
        - /v1/redirect-service-request-information
            op-s-0002
        - /v1/redirect-oam-request-information
            op-s-0003
        - /v1/inquire-oam-request-approvals
            op-s-0005
        - /v1/update-client
            op-s-0007
        - /v1/redirect-topology-change-information
            op-s-0009
        - /v1/update-operation-key
            op-s-0010
        - /v1/update-operation-client
            op-s-0011
        - /v1/bequeath-your-data-and-die
            op-s-1000
        ## All INDIVIDUAL service requests, which are updating an LTP, to be complemented
      consequent-requests:
        unicast:
          - ApplicationLayerTopology://v1/update-ltp
              op-c-0071
  - ServiceRequestCausesLtpDeletionRequest
      op-fc-0007
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
        ## All INDIVIDUAL service requests, which are deleting an LTP, to be complemented
      consequent-requests:
        unicast:
          - ApplicationLayerTopology://v1/delete-ltp-and-dependents
              op-c-0072
  - ServiceRequestCausesFcUpdateRequest
      op-fc-0008
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
        ## All INDIVIDUAL service requests, which are updating an FC, to be complemented
      consequent-requests:
        unicast:
          - ApplicationLayerTopology://v1/update-fc
              op-c-0073
  - ServiceRequestCausesFcPortUpdateRequest
      op-fc-0009
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
        ## All INDIVIDUAL service requests, which are updating an FC-Port, to be complemented
      consequent-requests:
        unicast:
          - ApplicationLayerTopology://v1/update-fc-port
              op-c-0074
  - ServiceRequestCausesFcPortDeletionRequest
      op-fc-0010
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
        - /v1/end-subscription
            op-s-0004
        ## All INDIVIDUAL service requests, which are deleting an FC-Port, to be complemented
      consequent-requests:
        unicast:
          - ApplicationLayerTopology://v1/delete-fc-port
              op-c-0075
  - OamRequestCausesLtpUpdateRequest
      op-fc-0011
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
      consequent-requests:
        unicast:
          - ApplicationLayerTopology://v1/update-ltp
              op-c-0071
  - OamRequestCausesLtpDeletionRequest
      op-fc-0012
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
      consequent-requests:
        unicast:
          - ApplicationLayerTopology://v1/delete-ltp-and-dependents
              op-c-0072
  - OamRequestCausesFcUpdateRequest
      op-fc-0013
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
      consequent-requests:
        unicast:
          - ApplicationLayerTopology://v1/update-fc
              op-c-0073
  - OamRequestCausesFcPortUpdateRequest
      op-fc-0014
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
      consequent-requests:
        unicast:
          - ApplicationLayerTopology://v1/update-fc-port
              op-c-0074
  - OamRequestCausesFcPortDeletionRequest
      op-fc-0015
      Invariant Process Snippet
      management-requests:
        operation-client-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-update:
          - /v1/redirect-topology-change-information
              op-s-0009
        fc-port-deletion:
        operation-client-deletion:
      initiating-requests:
      consequent-requests:
        unicast:
          - ApplicationLayerTopology://v1/delete-fc-port
              op-c-0075
  ## INDIVIDUAL Forwardings



