servers:
  operation-servers:
    own-oam:
      basic:
        - /v1/register-yourself
            op-s-0000
        - /v1/embed-yourself
            op-s-0001
        - /v1/redirect-service-request-information
            op-s-0002
        - /v1/redirect-oam-request-information
            op-s-0003
        - /v1/end-subscription
            op-s-0004
        - /v1/inquire-oam-request-approvals
            op-s-0005
        - /v1/update-client
            op-s-0007
        - /v1/list-ltps-and-fcs
            op-s-0008
        - /v1/redirect-topology-change-information
            op-s-0009
        - /v1/update-operation-key
            op-s-0010
        - /v1/update-operation-client
            op-s-0011
      individual:
        - /v1/bequeath-your-data-and-die
            op-s-1000
    service:
      basic:
        - /v1/inform-about-application
            op-s-2001
        - /v1/inform-about-application-in-generic-representation
            op-s-2002
        - /v1/inform-about-release-history
            op-s-2003
        - /v1/inform-about-release-history-in-generic-representation
            op-s-2004
      individual:
        - /v1/start-application-in-generic-representation
            op-s-3000
        ## Services specific to this application
  http-server:
    ## OwnApplicationName
    ## OwnReleaseNumber (e.g. 0.0.1)
    http-s-0000
  tpc-server:
    ## OwnIpAddress
    ## OwnTcpPort
    tcp-s-0000

clients:
  - OldRelease
      operation-clients:
        own-oam:
          basic:
            - /v1/bequeath-your-data-and-die
                op-c-0000
      http-client:
        OldRelease
        ## Number of Release to be substituted (e.g. 0.0.1)
        http-c-0000
      tcp:
        ## IpAddress of Release to be substituted
        ## TcpPort of Release to be substituted
        tcp-c-0000
  - NewRelease
      operation-clients:
        own-oam:
          individual:
            ## Services required for handing-over configuration or data during update
      http-client:
        NewRelease
        ## Number of substituting Release (e.g. 0.0.2)
        http-c-0010
      tcp:
        ## IpAddress of substituting Release
        ## TcpPort of substituting Release
        tcp-c-0010
  - RegistryOffice
      operation-clients:
        own-oam:
          basic:
            - /v1/register-application
                op-c-0020
            - /v1/relay-server-replacement
                op-c-0021
            - /v1/deregister-application
                op-c-0022
            - /v1/relay-operation-update
                op-c-0023
        service:
          basic:
            ## Clients specific to this application, but addressing all other applications
          individual:
            ## Clients specific to this application
      http-client:
        RegistryOffice
        [Current_ReleaseNumber_of_the_RegistryOffice]
        http-c-0020
      tcp:
        [Current_IP_address_of_the_RegistryOffice]
        [Current_TCP_port_of_the_RegistryOffice]
        tcp-c-0020
  - TypeApprovalRegister
      operation-clients:
        service:
          basic:
            ## Clients specific to this application, but addressing all other applications
          individual:
            ## Clients specific to this application
      http-client:
        TypeApprovalRegister
        [Current_ReleaseNumber_of_the_TypeApprovalRegister]
        http-c-2030
      tcp:
        [Current_IP_address_of_the_TypeApprovalRegister]
        [Current_TCP_port_of_the_TypeApprovalRegister]
        tcp-c-2030
  - ExecutionAndTraceLog
      operation-clients:
        own-oam:
          basic:
            - /v1/record-service-request
                op-c-0040
        service:
          basic:
            ## Clients specific to this application, but addressing all other applications
          individual:
            ## Clients specific to this application
      http-client:
        ExecutionAndTraceLog
        [Current_ReleaseNumber_of_the_ExecutionAndTraceLog]
        http-c-0040
      tcp:
        [Current_IP_address_of_the_ExecutionAndTraceLog]
        [Current_TCP_port_of_the_ExecutionAndTraceLog]
        tcp-c-0040
  - OamLog
      operation-clients:
        own-oam:
          basic:
            - /v1/record-oam-request
                op-c-0050
        service:
          basic:
            ## Clients specific to this application, but addressing all other applications
          individual:
            ## Clients specific to this application
      http-client:
        OamLog
        [Current_ReleaseNumber_of_the_OamLog]
        http-c-0050
      tcp:
        [Current_IP_address_of_the_OamLog]
        [Current_TCP_port_of_the_OamLog]
        tcp-c-0050
  - AdministratorAdministration
      operation-clients:
        own-oam:
          basic:
            - /v1/approve-oam-request
                op-c-0060
        service:
          basic:
            ## Clients specific to this application, but addressing all other applications
          individual:
            ## Clients specific to this application
      http-client:
        AdministratorAdministration
        [Current_ReleaseNumber_of_the_AdministratorAdministration]
        http-c-0060
      tcp:
        [Current_IP_address_of_the_AdministratorAdministration]
        [Current_TCP_port_of_the_AdministratorAdministration]
        tcp-c-0060
  - ApplicationLayerTopology
      operation-clients:
        own-oam:
          basic:
            - /v1/update-all-ltps-and-fcs
                op-c-0070
            - /v1/update-ltp
                op-c-0071
            - /v1/delete-ltp-and-dependents
                op-c-0072
            - /v1/update-fc
                op-c-0073
            - /v1/update-fc-port
                op-c-0074
            - /v1/delete-fc-port
                op-c-0075
        service:
          basic:
            ## Clients specific to this application, but addressing all other applications
          individual:
            ## Clients specific to this application
      http-client:
        ApplicationLayerTopology
        [Current_ReleaseNumber_of_the_ApplicationLayerTopology]
        http-c-0070
      tcp:
        [Current_IP_address_of_the_ApplicationLayerTopology]
        [Current_TCP_port_of_the_ApplicationLayerTopology]
        tcp-c-0070
  - OperationKeyManagement
      operation-clients:
        service:
          basic:
            ## Clients specific to this application, but addressing all other applications
          individual:
            ## Clients specific to this application
      http-client:
        OperationKeyManagement
        [Current_ReleaseNumber_of_the_OperationKeyManagement]
        http-c-2080
      tcp:
        [Current_IP_address_of_the_OperationKeyManagement]
        [Current_TCP_port_of_the_OperationKeyManagement]
        tcp-c-2080
  - CurrentController
      operation-clients:
        service:
          basic:
            ## Clients specific to this application, but addressing all other applications
          individual:
            ## Clients specific to this application
      http-client:
        CurrentController
        [Current_ReleaseNumber_of_the_CurrentController]
        http-c-2300
      tcp:
        [Current_IP_address_of_the_CurrentController]
        [Current_TCP_port_of_the_CurrentController]
        tcp-c-2300
