profiles:

  - profile-name: ActionProfile
    uuid: string
      pattern: '^[a-z]{2,6}-([0-9]+)-([0-9]+)-([0-9]+)-action-p-10[0-9]{2}$'
    operation-name: string
    label: string
    request: string
    input-value-list:
      - field-name: string
        unit: string
    display-in-new-browser-window: boolean

  - profile-name: IntegerProfile
    uuid: string
      pattern: '^[a-z]{2,6}-([0-9]+)-([0-9]+)-([0-9]+)-integer-p-10[0-9]{2}$'
    integer-name: string
    unit: string
    minimum: integer
    maximum: integer
    configured-value: integer

  - profile-name: StringProfile
    uuid: string
      pattern: '^[a-z]{2,6}-([0-9]+)-([0-9]+)-([0-9]+)-string-p-10[0-9]{2}$'
    string-name: string
    enumeration: array
    pattern: string
    configured-value: string

## Add further Profile definitions, if required